### ISSUE TITLE
Problems connecting with twitch

### ISSUE THREAD

**Issue by ingostrohmeier** [MikeJewski/ArduinoDeck#3]
**Issue**: Twitch chat functions of Arduino Deck not working

**My Setup**: I created a oauth Key with the link in the instructions and pasted it into the Setup.txt without the "oauth:". I added my channel name in the ChannelName line, in lowercase letters.
Added a button with the custom message function in the ArduinoDeck program, saved the layout and uploaded it to the Arduino. Started the deck in the ArduinoDeck program.

**Result**: When pressing any of the custom message or chat mode buttons, nothing happens. My Twitch Channel seems to be connected, because the deck shows the viewer count correctly according to the Twitch dashboard, and the uptime timer also works (although the timer starts at 5:00 instead of 0:00)

I added my Setup file below:
[Setup.txt](https://github.com/MikeJewski/ArduinoDeck/files/1463610/Setup.txt)

**Comment by MikeJewski** [comment]
Issue occured when changing over the methods, TwitchChatKey was being handled improperly. Twitch chat custom commands should now be working correctly, but the follower-only mode is still somewhat not working perfectly.
