### ISSUE TITLE
Failed too execute script ArduinoConnect

### ISSUE THREAD

**Issue by ghost** [MikeJewski/ArduinoDeck#6]
Tried opening the application and arduinoconnect but am greeted with Failed too execute script ArduinoConnect

The board is on the right COM port

**Comment by MikeJewski** [comment]
I still have to update the code to have a crash/issue log so we can figure this out, but I will add an extra version of each of the exe's which should print the issues. Download the new version of ArduinoConnect and ArduinoDeck from the Debug folder, and replace the original files (put them in another folder so you don't have to redownload), and then launch it by running it from the cmd line. Let me know what error you get

**Comment by RonnieeTV** [comment]
Thanks, outputted this.
There is a Setup.txt in the main folder and I have configured it.


```
> C:\Users\Ronnie>C:\Users\Ronnie\Desktop\ArduinoDeck\src\ArduinoConnect.exe
> Traceback (most recent call last):
>   File "ArduinoConnect.py", line 20, in <module>
> IOError: [Errno 2] No such file or directory: 'Setup.txt'
> Failed to execute script ArduinoConnect
```

**Comment by ghost** [comment]
Thanks, outputted this.
I do have the txt file in the main folder and it is configured.


```
C:\Users\Ronnie>C:\Users\Ronnie\Desktop\ArduinoDeck\src\ArduinoConnect.exe
Traceback (most recent call last):
  File "ArduinoConnect.py", line 20, in <module>
IOError: [Errno 2] No such file or directory: 'Setup.txt'
Failed to execute script ArduinoConnect
```

**Comment by ghost** [comment]
Think I may have got it working.

Now getting this when trying to highlight a box in the app (having to double click)
```
: invalid bitmap
Traceback (most recent call last):
  File "site-packages\wx\lib\buttons.py", line 491, in OnPaint
  File "site-packages\wx\lib\buttons.py", line 830, in DrawLabel
wx._core.wxAssertionError: C++ assertion "bmp.IsOk()" failed at ..\..\src\msw\dc.cpp(1313) in wxMSWDCImpl::DoDrawBitmap(): invalid bitmap in wxMSWDCImpl::DrawBitmap
```

**Comment by MikeJewski** [comment]
did you use the image converter to create the bmps?

**Comment by MikeJewski** [comment]
If this doesn't get a response by the end of the week, I am going to mark this as closed
